title: Cindy Yuristie
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: '/cindyyuristie.github.io' # the subpath of your site, e.g. /blog
url: 'htpps://cindyyuristie.github.io' # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/cindyyuristie.github.io'
blog_theme: dark # Or use dark

# Profile information
name: Cindy Yuristie
tagline: Mahasiswi Sistem Informasi
about-description: Assalamualaikumwarahmatullahiwaarakatuh, Saya Cindy Yuristie berumur 21th yang lahir pada 16 Januari 1996. Saya kuliah di Universitas Islam Negeri Sultan Syarif Kasim Riau fakultas Sains dan Teknologi pada jurusan Sistem Informasi. Sekarang saya kuliah pada semester 7. 
pic: cindyyur.jpg  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: cindyyuristie.cy@gmail.com # Add your Email address
phone: 0821 1025 6317 # Add your Phone number
website: cindyyuristie.cy # Add your website, do not add http://
linkedin: CIndyyuristie # Add your Linkedin handle
github: Cindyyuristie # Add your Github handle
twitter: '@cindyyuristie' # Add your Twitter handle

# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
